### PR TITLE
Reorg for testing + Github Actions!!

### PR DESCRIPTION
**Pull request by nickumia**
There's a lot in here, feel free to completely reject it 😆 

Changes:
- Documentation is separated from code. (It's easier to see if you view the entire directory and not the diff)
- Python code has been partially linted

New Additions:
- ROS Architecture encapsulated in docker-compose environment.
- Tests are run in Github Actions

TODO:
- [ ] Finish cleaning up code linting
- [ ] Add tests for the code snippets that were actually in the repo to begin with.
- [ ] Strip out the rest of the code from `Robotics Tool` dir

### CODE REVIEW

**Comment by nickumia** [comment]
Successful Github Actions Run: https://github.com/nickumia/MRF-SDN/actions/runs/1834962361

**Comment by waseemhnyc** [comment]
@nickumia if you could fix the merge conflicts we could go ahead and merge this in

**Comment by nickumia** [comment]
@waseemhnyc I think it's good to go.  Key points:
- Successful github action run: https://github.com/nickumia/MRF-SDN/actions/runs/4954494031
- You should probably change `master` to `main` (just good practice..)
- For the lint that is failing, we should probably take care of that in a new PR since this one is already unwieldy 😬 
- Also, don't forget to enable github action runs on your main repo!

**Comment by waseemhnyc** [comment]
Thanks @nickumia!!

**Pull request merged**
